local ts=game:GetService("TweenService");
local cameraShake=require(127899128442444);
local dynamicExplosion = require(11380416673);
local sf=workspace:FindFirstChild("MusicFolder") or Instance.new('Folder',workspace);
sf.Name="MusicFolder";
function makeSound(id,vol,loop,name, pitch)
    pitch = pitch or 1;
    local s = Instance.new('Sound', sf);
    s.SoundId = id;
    s.Volume = vol;
    s.Looped = loop;
    s.Pitch = pitch;
    s.Name = name;
    return s;
end;
local ann1 = sf:FindFirstChild('evacatonce') or makeSound('rbxassetid://1474008656',1.5,false,'evacatonce');
local ann2 = sf:FindFirstChild('overheat') or makeSound('rbxassetid://159445410',1.5,false,'overheat');
local evac = sf:FindFirstChild('evac') or makeSound('rbxassetid://147296378',1.5,false,'evac');
local alarm = sf:FindFirstChild('alarm') or makeSound('rbxassetid://2451364019',1.5,true,'alarm');
local alarm2 = sf:FindFirstChild('alarm2') or makeSound('rbxassetid://109606894712055',1.5,false,'alarm2',1.1);
local ann3 = sf:FindFirstChild('critical') or makeSound('rbxassetid://168877716',1.5,false,'critical');
local ann4 = sf:FindFirstChild('safeguards') or makeSound('rbxassetid://147296324',1.5,false,'safeguards');
local metalexplosion = sf:FindFirstChild('metalexplosion') or makeSound('rbxassetid://178962800', 1, false, 'metalexplosion');
local shockwave = sf:FindFirstChild('shockwave') or makeSound('rbxassetid://610327604', 2, false, 'shockwave');
local kaboom = sf:FindFirstChild('kaboom') or makeSound('rbxassetid://131026234',1.5,false,'kaboom');
local countdown=sf:FindFirstChild('tentozero') or makeSound("rbxassetid://15487574881",2,false,'tentozero');
local sdm1=sf:FindFirstChild('t6min') or makeSound("rbxassetid://1000895732",1.2,false,'t6min');
local sdm2=sf:FindFirstChild('selfdestruct') or makeSound("rbxassetid://1002834205",1.2,false,'selfdestruct');
local music1=sf:FindFirstChild('music1') or makeSound("rbxassetid://9254549777",1,false,'music1');
local music2=sf:FindFirstChild('music2') or makeSound("rbxassetid://9254568037",1,false,'music2');
local music3=sf:FindFirstChild('music3') or makeSound("rbxassetid://9254607488",1,false,'music3');
local music4=sf:FindFirstChild('music4') or makeSound("rbxassetid://9254632812",1,false,'music4');
function makeHint()
    local timerHint = Instance.new('ScreenGui', script);
    timerHint.Name = 'h';
    local hintFrame = Instance.new('Frame', timerHint);
    hintFrame.Size = UDim2.new(1,0,0.04,0);
    hintFrame.Position = UDim2.new(0.5,0,0,0);
    hintFrame.AnchorPoint = Vector2.new(0.5,0);
    hintFrame.BackgroundColor3 = Color3.new(0.117647, 0.117647, 0.117647);
    hintFrame.BackgroundTransparency = 0.7;
    hintFrame.Name = 'f';
    local h = Instance.new('TextLabel', hintFrame);
    h.Size = UDim2.new(1,-10,1,-10);
    h.Position = UDim2.new(0.5,0,0.5,0);
    h.AnchorPoint = Vector2.new(0.5,0.5);
    h.TextColor3 = Color3.new(1,1,1);
    h.TextScaled = true;
    h.BackgroundTransparency = 1;
    h.Name = 't';
    return timerHint;
end;
function finale()
    music4:Play();
    task.wait(33);
    countdown:Play();
    task.wait(12);
    kaboom:Play();
    cameraShake:shakeCamera(nil,10,10,3.6,1,5);
end;
while not music1.IsLoaded do
  task.wait();
end;
ann4:Play();
task.wait(5);
music1:Play();
sdm1:Play();
task.wait(36);
ann2:Play();
task.wait(5);
alarm2:Play();
shockwave:Play();
cameraShake:shakeCamera(nil,4,10,3.6,1,5);
task.wait(10);
ann3:Play();
alarm2:Play();
task.wait(8);
evac:Play();
task.wait(2);
alarm2:Play();
shockwave:Play();
cameraShake:shakeCamera(nil,4,10,3.6,1,5);
task.wait(10);
ann1:Play();
alarm2:Play();
task.wait(30);
ann2:Play();
shockwave:Play();
cameraShake:shakeCamera(nil,4,10,3.6,1,5);
task.wait(19);
music2:Play();
task.wait(120);
music3:Play();
task.wait(51);
sdm2:Play();
task.wait(24);
local timer = 90;
local timerHint = makeHint();
timerHint.f.t.Text ='Explosion in: '..timer;
for _,plr in pairs(game:GetService('Players'):GetPlayers()) do
    if plr then
        local gui = timerHint:Clone();
        gui.Parent = plr.PlayerGui;
        game:GetService('Debris'):AddItem(gui, 0.99);
    end;
end;
for i=1,timer do
    local ct = timer - i;
    timerHint.f.t.Text ='Explosion in: '..ct;
    if ct == 45 or timerHint.f.t.Text == 'Explosion in: 45' then
        music3:Stop();
        task.spawn(finale);
    end;
    for _,plr in pairs(game:GetService('Players'):GetPlayers()) do
        if plr then
            local gui = timerHint:Clone();
            gui.Parent = plr.PlayerGui;
            game:GetService('Debris'):AddItem(gui, 0.99);
        end;
    end;
    if ct == 10 or timerHint.f.t.Text == 'Explosion in: 10' then
        break;
    end;
    task.wait(1);
end;